Repository LucidVR/opengloves-driver, pull requests merged in 2021-08, with the labels that each got.

#108 Release v0.4
  .clang-format
  .editorconfig
  .gitignore
  BUILDING.md
  CMakeLists.txt
  README.md
  include/Calibration.h
  include/Communication/BTSerialCommunicationManager.h
  include/Communication/CommunicationManager.h
  include/Communication/SerialCommunicationManager.h
  include/ControllerDiscovery.h
  include/ControllerPose.h
  include/DeviceConfiguration.h
  include/DeviceDriver/KnuckleDriver.h
  include/DeviceDriver/LucidGloveDriver.h
  include/DeviceProvider.h
  include/Encode/AlphaEncodingManager.h
  include/Encode/EncodingManager.h
  include/Encode/LegacyEncodingManager.h
  include/ForceFeedback.h
  include/Quaternion.h
  include/Util/NamedPipe.h
  openglove/bin/win64/DLL GOES HERE.txt
  openglove/resources/input/openglove_profile.json
  openglove/resources/settings/default.vrsettings
  overlay/CMakeLists.txt
  overlay/main.cpp
  overlay/main.h
  src/Bones.cpp
  src/Calibration.cpp
  src/Communication/BTSerialCommunicationManager.cpp
  src/Communication/SerialCommunicationManager.cpp
  src/ControllerDiscovery.cpp
  src/ControllerPose.cpp
  src/DeviceDriver/KnuckleDriver.cpp
  src/DeviceDriver/LucidGloveDriver.cpp
  src/DeviceProvider.cpp
  src/Encode/AlphaEncodingManager.cpp
  src/Encode/LegacyEncodingManager.cpp
  src/ForceFeedback.cpp
  src/Quaternion.cpp
  src/Util/NamedPipe.cpp
Labels: release

#121 Added configuration for baud rate
  include/DeviceConfiguration.h
  openglove/resources/settings/default.vrsettings
  src/Communication/SerialCommunicationManager.cpp
  src/DeviceProvider.cpp
Labels: enhancement

#123 Fix incorrectly documented finger orders in alpha encoding
  src/Encode/AlphaEncodingManager.cpp
Labels: documentation
